name: Extract Kernel from LineageOS 22.2

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      PAT: ${{ secrets.ACCESS_TOKEN }}      
      GITHUB_WORKSPACE: /home/runner/work/Redmi8_Kernel_Patches/Redmi8_Kernel_Patches
    timeout-minutes: 360

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: "Optimize Disk Space"
      uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
      with:
        operate_sudo: "True"
        general_include: ".+"
        general_exclude: |-
          ^GCC$
          ^G\+\+$
          Clang
          LLVM
        docker_include: ".+"
        docker_prune: "False"
        docker_clean: "False"
        apt_prune: "False"
        apt_clean: "False"
        homebrew_prune: "True"
        homebrew_clean: "True"
        npm_prune: "True"
        npm_clean: "True"
        os_swap: "True"

    - name: Freeing up disk space
      uses: easimon/maximize-build-space@master
      with: 
        root-reserve-mb: 2048
        swap-size-mb: 1
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'false'

    - name: Clean root partition
      run: |
        sudo rm -rf /tmp/*
        sudo rm -rf /var/cache/apt/archives/*                 

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Setup Environment
      run: |       
        sudo apt-get update
        sudo apt-get install -y git curl python3 python3-pip
        sudo apt install brotli

    - name: Install Repo Tool
      run: |          
        mkdir -p bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > bin/repo
        chmod a+x bin/repo
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Git Config
      run: |
        git config --global user.email "whmyc801@gmail.com"
        git config --global user.name "yu13140"

    - name: Initialize Repository
      run: |          
        mkdir lineage      
        cd lineage
        repo init -u https://github.com/LineageOS/android.git -b lineage-22.2 --depth=1
        wget https://raw.githubusercontent.com/yu13140/Redmi8_Kernel_Patches/refs/heads/main/yuzkernel.sh
        bash yuzkernel.sh
        echo "======Ending Repo======"
        sudo rm -f yuzkernel.sh
        
    - name: Clone Device File
      run: |
        git clone -b lineage-22.2 https://github.com/LineageOS/android_device_xiaomi_Mi439.git --depth=1
        mkdir -p lineage/device/xiaomi/Mi439/
        sudo mv android_device_xiaomi_Mi439/* lineage/device/xiaomi/Mi439/
        git clone -b lineage-22.2 https://github.com/LineageOS/android_device_xiaomi_mithorium-common.git --depth=1
        mkdir -p lineage/device/xiaomi/mithorium-common/
        sudo mv android_device_xiaomi_mithorium-common/* lineage/device/xiaomi/mithorium-common/
        
        
    - name: Extract proprietary blobs
      run: |
        mkdir -p android/system_dump/
        cd android/system_dump/
        wget --output-document=lineageos.zip https://mirror.tuna.tsinghua.edu.cn/lineage-rom/full/Mi439/20250424/lineage-22.2-20250424-nightly-Mi439-signed.zip
        unzip lineageos.zip system.transfer.list system.new.dat* vendor.transfer.list vendor.new.dat*
        rm -f lineage.zip
        brotli --decompress --output=system.new.dat system.new.dat.br
        brotli --decompress --output=vendor.new.dat vendor.new.dat.br
        git clone https://github.com/xpirt/sdat2img
        python sdat2img/sdat2img.py system.transfer.list system.new.dat system.img
        sudo rm -f system.new.dat system.new.dat.br
        python sdat2img/sdat2img.py vendor.transfer.list vendor.new.dat vendor.img
        sudo rm -f vendor.new.dat vendor.new.dat.br
        mkdir -p system/
        sudo mount system.img system/
        sudo rm -rf system/vendor
        mkdir -p system/vendor
        sudo mount vendor.img system/vendor/
        sudo rm -rf sdat2img/
        cd $GITHUB_WORKSPACE/lineage/device/xiaomi/Mi439
        ./extract-files.sh /home/runner/work/Redmi8_Kernel_Patches/Redmi8_Kernel_Patches/android/system_dump/
        cd $GITHUB_WORKSPACE
        sudo umount android/system_dump/system/vendor/
        sudo umount android/system_dump/system/
        sudo rm -rf android/system_dump/
        sudo rm -rf lineage/device/xiaomi/mithorium-common/

    - name: Sync Source Code
      run: |
        cd lineage
        . build/envsetup.sh
        breakfast "Mi439"

    - name: Extract Kernel Files
      run: |      
        ls lineage/kernel/xiaomi/      
        if [ ! -d "./lineage/kernel/xiaomi/sdm439/" ]; then
          echo "❌ Kernel files not found!"
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: olive-kernel
        path: /home/runner/work/Redmi8_Kernel_Patches/Redmi8_Kernel_Patches/lineage/kernel/xiaomi/sdm439/

    - name: Commit to Repository
      run: |
        cd lineage/kernel/xiaomi/sdm439/         
        git remote set-url origin "https://${PAT}@github.com/yu13140/LineageOS_Kernel_Redmi8.git"        
        git add .
        git commit -m "Update kernel files $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push -u origin main