name: Extract Kernel from LineageOS 21

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      PAT: ${{ secrets.ACCESS_TOKEN }}    
    timeout-minutes: 360

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: "Optimize Disk Space"
      uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
      with:
        operate_sudo: "True"
        general_include: ".+"
        general_exclude: |-
          ^GCC$
          ^G\+\+$
          Clang
          LLVM
        docker_include: ".+"
        docker_prune: "False"
        docker_clean: "False"
        apt_prune: "False"
        apt_clean: "False"
        homebrew_prune: "True"
        homebrew_clean: "True"
        npm_prune: "True"
        npm_clean: "True"
        os_swap: "True"

    - name: Freeing up disk space
      uses: easimon/maximize-build-space@master
      with: 
        root-reserve-mb: 2048
        swap-size-mb: 1
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'false'

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl python3 python3-pip

    - name: Install Repo Tool
      run: |
        pwd
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Git Config
      run: |
        git config --global user.email "whmyc801@gmail.com"
        git config --global user.name "yu13140"

    - name: Initialize Repository
      run: |
        mkdir ~/lineage
        cd ~/lineage
        repo init -u https://github.com/LineageOS/android.git -b lineage-21.0
        repo sync -j16

    - name: Sync Source Code
      run: |
        . build/envsetup.sh
        breakfast "Mi439"

    - name: Extract Kernel Files
      run: |
        ls ~/lineage/kernel/xiaomi/
        # 验证内核文件存在
        if [ ! -d "~/lineage/kernel/xiaomi/sdm439/" ]; then
          echo "❌ Kernel files not found!"
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: olive-kernel
        path: kernel_files/

    - name: Commit to Repository
      run: |
        cd ~/lineage/kernel/xiaomi/sdm439/         
        git remote set-url origin "https://${PAT}@github.com/yu13140/LineageOS_Kernel_Redmi8.git"        
        git add .
        git commit -m "Update kernel files $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push -u origin main